### ISSUE TITLE
Update `entry` to `input`

### ISSUE THREAD

**Issue by AngusFu** [TrySound/rollup-plugin-memory#2]
Rollup option `entry` has been deprecated, use `input` instead.  I wonder if you want an update for this package.

BTW, according to [this issue](https://github.com/Rich-Harris/buble/issues/86), better to choose another param name for `options(options)` given buble upgraded.

**Comment by nathancahill** [comment]
The `options` issue has been fixed in Buble.

**Comment by TrySound** [comment]
Deprecated in favor of https://github.com/rollup/rollup-plugin-virtual
